--- 
abstract: Make the current Catalyst
author: 
  - Jonathan Rockway, C<< <jrockway at cpan.org> >>
build_requires: 
  Devel::Cycle: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Component-ACCEPT_CONTEXT
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 0
  Scalar::Util: 0
version: 0.05
