abstract: Make the current Catalyst
author: Jonathan Rockway, C<< <jrockway at cpan.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Component-ACCEPT_CONTEXT
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 0
version: 0.02
